feat(framework-core): main interface for create review on a pull request
googleapis/code-suggester pull request #114
Opened 2020-09-10 03:14 UTC by TomKristie

Main interface for frame-work core, documentation + review comments:
1. renamin `comment` to `reviewPullRequest`
2. more tests!

PR commit for #105

2020-09-10 03:43 UTC, chingor13 requested changes
Thanks Kristie!

2020-09-10 03:43 UTC, chingor13 commented on src/default-options-handler.ts
> +export function addRevuewCommentsDefaults(
```suggestion
export function addReviewCommentsDefaults(
```

2020-09-10 03:43 UTC, chingor13 commented on src/index.ts
> +    `Successfully created a review on pull requestt: ${gitHubConfigs.pullNumber}.`
```suggestion
    `Successfully created a review on pull request: ${gitHubConfigs.pullNumber}.`
```

2020-09-10 03:43 UTC, chingor13 commented on src/default-options-handler.ts
> +  return reviewCommentSettings;
Let's declare the return type in the signature and then we can return the object directly.

2020-09-10 03:43 UTC, chingor13 commented on src/index.ts
> +  const gitHubConfigs = addRevuewCommentsDefaults(options);
Can we name this `createReviewComment` as it's a `CreateReviewComment` type?

2020-09-10 17:09 UTC, bcoe approved these changes
This is looking solid to me once @chingor13's typo and naming nits are addressed.

2020-09-11 05:00 UTC, chingor13 approved these changes

2020-09-11 05:00 UTC, merged