Create/Pass commit date to commit for signing
googleapis/code-suggester pull request #485
Opened 2024-01-30 16:34 UTC by IchordeDionysos

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/code-suggester/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #337 🦕

2024-02-20 17:09 UTC, IchordeDionysos commented
@googleapis/github-automation can someone review my PR, this would unblock issues in release-please to sign commits.

2024-05-03 09:53 UTC, IchordeDionysos commented
@chingor13 @SurferJeffAtGoogle @bshaffer hey it would be cool to get some feedback whether this is something we can add to the package.

As it is currently the commit signing capability is broken and does not work ...

2024-08-20 16:05 UTC, Sese-Schneider approved these changes

2024-08-20 16:07 UTC, IchordeDionysos commented
@sofisl @danieljbruce do you see any possibility to get this merged? ☺️ 
This would unblock using release-please in situations where commit signing is required.

2025-02-27 00:45 UTC, chingor13 requested changes
Sorry, we're finally getting back to PRs on this repo.

The tests are not passing and this branch is not writeable so we can't help update it

2025-02-27 00:45 UTC, chingor13 commented on src/types.ts
> +  date?: Date;
I don't think I follow why date is part of the UserData as opposed to the commit

2025-02-27 00:45 UTC, chingor13 commented on src/types.ts
> +  generateSignature(commit: CommitDataWithRequiredDate): Promise<string>;
This seems like a breaking change which makes additional inputs required. Does this actually need to be a required field?

2025-03-22 13:13 UTC, IchordeDionysos reviewed
@chingor13 sorry that I only responded now. Have just seen it today.
I fixed the tests and added a bit more context to the why I tackled the changes in a particular way.

2025-06-27 14:39 UTC, erikpaasonen commented
@IchordeDionysos can this branch get synced please? Maybe that's what @chingor13 is waiting on for re-review?

Eager to see this PR merged so that Release Please (a consumer of code-suggester) can sign commits in environments where code signing is a hard requirement.

2025-09-17 20:11 UTC, eth-limo commented
Are there any updates on this? It would be great to finally get signing support for the release-please action.

2026-07-14 13:39 UTC, codyoss commented
Thank you for your contribution to code-suggester. This repository is currently in the process of being archived and as such all existing pull requests are being closed.

2026-07-14 13:39 UTC, closed without merging